#!/bin/bash
# ======================================================================
# Rxiv-Maker Docker Usage Instructions  
# ======================================================================
# Shows usage instructions for the NEW terminal-focused Docker workflow
# NEW POLICY: rxiv-maker is pre-installed via UV during build time

echo "📚 Rxiv-Maker Docker Container - Usage Instructions (NEW POLICY)"
echo "================================================================="
echo ""
echo "🎯 TERMINAL-BASED WORKFLOW (PRE-INSTALLED RXIV-MAKER)"
echo "This container includes rxiv-maker pre-installed via UV and ready for immediate use."
echo "No runtime dependency installation needed!"
echo ""
echo "🚀 QUICK START:"
echo ""
echo "1️⃣ Start interactive container with your manuscript:"
echo "   docker run -it --rm -v \$(pwd):/workspace henriqueslab/rxiv-maker-base:latest"
echo ""
echo "2️⃣ Optional: Set up workspace (run inside container):"
echo "   workspace-setup.sh"
echo ""
echo "3️⃣ Use rxiv-maker commands directly (pre-installed!):"
echo "   rxiv pdf ./my-manuscript/"
echo "   rxiv validate ./my-manuscript/"
echo "   rxiv --help"
echo ""
echo "🔧 ALTERNATIVE WORKFLOWS:"
echo ""
echo "📁 Direct command execution (no interactive shell needed):"
echo "   docker run --rm -v \$(pwd):/workspace henriqueslab/rxiv-maker-base:latest rxiv pdf ."
echo "   docker run --rm -v \$(pwd):/workspace henriqueslab/rxiv-maker-base:latest rxiv validate ."
echo ""
echo "⚡ Quick workspace setup and command:"
echo "   docker run -it --rm -v \$(pwd):/workspace henriqueslab/rxiv-maker-base:latest bash -c 'workspace-setup.sh && rxiv pdf .'"
echo ""
echo "📦 INCLUDED TOOLS (PRE-INSTALLED):"
echo "   • ✅ rxiv-maker (latest via UV, installed during build)"
echo "   • ✅ Complete LaTeX environment (texlive)"  
echo "   • ✅ Python 3.11 with scientific libraries"
echo "   • ✅ R with graphics packages"
echo "   • ✅ UV package manager"
echo "   • ✅ All system dependencies"
echo ""
echo "🆕 NEW ARCHITECTURE BENEFITS:"
echo "   • 🚀 Faster startup (no runtime dependency installation)"
echo "   • 🔒 Consistent versions (locked during build time)"
echo "   • 🎯 Direct terminal usage (just run rxiv commands)"
echo "   • 📦 Self-contained (everything pre-installed)"
echo ""
echo "💡 USAGE TIPS:"
echo "   • Mount your manuscript directory to /workspace"
echo "   • Use absolute paths when mounting volumes"
echo "   • All rxiv-maker commands work immediately"
echo "   • No setup scripts required (but workspace-setup.sh available for convenience)"
echo ""
echo "🆘 HELP:"
echo "   • rxiv --help           - Rxiv-maker command help"
echo "   • usage.sh             - This usage guide"
echo "   • workspace-setup.sh   - Interactive workspace setup helper"
echo "   • rxiv --version       - Check pre-installed version"
echo ""
echo "🔄 VERSION INFORMATION:"
rxiv --version 2>/dev/null && echo "✅ Rxiv-maker ready for use!" || echo "❌ Rxiv-maker installation issue"
